[server]
host = "localhost"
port = 9999
max-threads = 12

[logging]
log-encoding = "UTF-8"
log-file = "hubLog.log"
log-level = "INFO"
log-timestamp-format = "dd-MM-yyyy HH:mm:ss.SSS"
plain-logs = true

[events]
publish = "tcp://*:9992"
subscribe = "tcp://*:9993"
